org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Common
minecraft_version=26.2
neoform_version=26.2-1

# NeoForge
neoforge_version=26.2.0.3-beta

# Fabric
fabric_loader_version=0.19.3
fabric_api_version=0.152.2+26.2

# MC dependencies
jetbrains_annotations_version=26.0.1
mixin_version=0.16.5+mixin.0.8.7
mixin_extras_version=0.5.3
asm_version=9.9.1

## Mod Properties
mod_id=structureexplorer
mod_name=Structure Explorer
mod_version=1.1.5
mod_description=Use `/visits` command to see all the structures you've visited.
sources_url=
issues_url=
license_url=
homepage_url=

# Publishing
mod_group_id=in.fellaguy
curseforge_id=
modrinth_id=
